export declare const defaultFields: {
    commentFields: {
        commentId: string;
        content: string;
        createDate: string;
        publisher: string;
        likeCount: string;
        like: string;
        updateDate: string;
        username: string;
        avatar: string;
        userId: string;
        children: string;
        subComment: string;
        parentId: string;
        replyId: string;
        reply: string;
        formatTime: boolean;
        replyRender: boolean;
        likeRender: boolean;
        ipAddress: string;
        level: string;
    };
    dataLevel: number;
    actions: boolean;
    useEmojis: boolean;
    emojis: never[];
    list: string;
    hasMore: string;
    foldBtnPosition: string;
    lines: number;
};
